
import { Language, TestDefinition } from './types';

export const TRANSLATIONS = {
  [Language.EN]: {
    heroTitle: "Unlock Your Potential",
    heroSub: "Pass deep behavioral and physical tests to join our exclusive community.",
    ctaTests: "Start Testing",
    ctaTokens: "Get Tokens",
    balance: "Balance",
    langSwitch: "RU",
    reviews: "User Reviews",
    startTest: "Start Test",
    continue: "Continue",
    back: "Back",
    finish: "Finish",
    results: "Your Results",
    joinChannel: "Join Private Channel",
    agentPanel: "Agent Dashboard",
    adminPanel: "Admin Panel",
    sendTokens: "Send Tokens",
    recipient: "Recipient ID",
    amount: "Amount",
    success: "Success!",
    tokenHistory: "Token History",
    allTestsPackage: "Full Bundle (5 Tests)",
    buyBundle: "Buy Bundle for 450 Tokens",
    price: "Price",
    footerCaption: "Empowering your journey through data-driven insights and physical excellence.",
    recentResults: "My Recent Results",
    noResults: "No tests completed yet.",
    quickStart: "Quick Start",
    myAccount: "My Account",
    profile: "Profile",
    buyTokens: "Purchase Tokens",
    packageStarter: "Starter Pack",
    packagePro: "Pro Pack",
    packageElite: "Elite Pack",
    tokensCount: "Tokens",
    buyNow: "Buy Now",
    transactionHistory: "Transaction History",
    accountStats: "Account Statistics",
    selectCurrency: "Select Currency",
    payWithCrypto: "Pay with Crypto",
    payWithCard: "Pay with Card",
    cryptoSubtitle: "Fast & Anonymous",
    cardSubtitle: "Visa, Mastercard, MIR",
    confirmPayment: "Confirm Payment",
    foodScan: "Food Scanner",
    scanCTA: "Scan Your Meal",
    analyzing: "AI Analyzing Food...",
    calories: "Calories",
    protein: "Protein",
    carbs: "Carbs",
    fat: "Fat",
    takePhoto: "Take Photo",
    uploadImage: "Upload Image",
    analysisResult: "Nutritional Analysis",
    insufficientTokens: "Insufficient tokens to scan food (costs 50 tokens)."
  },
  [Language.RU]: {
    heroTitle: "Раскрой свой потенциал",
    heroSub: "Пройди глубокие поведенческие и физические тесты, чтобы вступить в наше закрытое сообщество.",
    ctaTests: "Начать тесты",
    ctaTokens: "Купить токены",
    balance: "Баланс",
    langSwitch: "ES",
    reviews: "Отзывы",
    startTest: "Начать тест",
    continue: "Далее",
    back: "Назад",
    finish: "Завершить",
    results: "Ваши результаты",
    joinChannel: "Вступить в закрытый канал",
    agentPanel: "Панель Агента",
    adminPanel: "Админка",
    sendTokens: "Отправить токены",
    recipient: "ID получателя",
    amount: "Количество",
    success: "Успех!",
    tokenHistory: "История токенов",
    allTestsPackage: "Пакет (все 5 тестов)",
    buyBundle: "Купить пакет за 450 токенов",
    price: "Цена",
    footerCaption: "Расширяем ваши возможности через инсайты на основе данных и физическое совершенство.",
    recentResults: "Мои результаты",
    noResults: "Тесты еще не пройдены.",
    quickStart: "Быстрый старт",
    myAccount: "Мой аккаунт",
    profile: "Профиль",
    buyTokens: "Пополнение баланса",
    packageStarter: "Стартовый",
    packagePro: "Профи",
    packageElite: "Элитный",
    tokensCount: "Токенов",
    buyNow: "Купить",
    transactionHistory: "История транзакций",
    accountStats: "Статистика аккаунта",
    selectCurrency: "Выберите валюту",
    payWithCrypto: "Оплата Криптовалютой",
    payWithCard: "Оплата Картой",
    cryptoSubtitle: "Быстро и Анонимно",
    cardSubtitle: "Visa, Mastercard, МИР",
    confirmPayment: "Подтвердить оплату",
    foodScan: "Скан еды",
    scanCTA: "Сканировать блюдо",
    analyzing: "ИИ анализирует еду...",
    calories: "Калории",
    protein: "Белки",
    carbs: "Углеводы",
    fat: "Жиры",
    takePhoto: "Сделать фото",
    uploadImage: "Загрузить фото",
    analysisResult: "Анализ питания",
    insufficientTokens: "Недостаточно токенов (нужно 50)."
  },
  [Language.ES]: {
    heroTitle: "Libera tu Potencial",
    heroSub: "Pasa pruebas físicas y de comportamiento para unirte a nuestra comunidad exclusiva.",
    ctaTests: "Empezar Pruebas",
    ctaTokens: "Obtener Tokens",
    balance: "Saldo",
    langSwitch: "HI",
    reviews: "Reseñas de Usuarios",
    startTest: "Empezar Prueba",
    continue: "Continuar",
    back: "Atrás",
    finish: "Finalizar",
    results: "Tus Resultados",
    joinChannel: "Unirse al Canal Privado",
    agentPanel: "Panel de Agente",
    adminPanel: "Panel de Admin",
    sendTokens: "Enviar Tokens",
    recipient: "ID del Destinatario",
    amount: "Cantidad",
    success: "¡Éxito!",
    tokenHistory: "Historial de Tokens",
    allTestsPackage: "Paquete Completo (5 Pruebas)",
    buyBundle: "Comprar Paquete por 450 Tokens",
    price: "Precio",
    footerCaption: "Potenciando tu camino a través de datos y excelencia física.",
    recentResults: "Mis Resultados Recientes",
    noResults: "Aún no se han completado pruebas.",
    quickStart: "Inicio Rápido",
    myAccount: "Mi Cuenta",
    profile: "Perfil",
    buyTokens: "Comprar Tokens",
    packageStarter: "Paquete Inicial",
    packagePro: "Paquete Pro",
    packageElite: "Paquete Elite",
    tokensCount: "Tokens",
    buyNow: "Comprar Ahora",
    transactionHistory: "Historial de Transacciones",
    accountStats: "Estadísticas de la Cuenta",
    selectCurrency: "Seleccionar Moneda",
    payWithCrypto: "Pagar con Cripto",
    payWithCard: "Pagar con Tarjeta",
    cryptoSubtitle: "Rápido y Anónimo",
    cardSubtitle: "Visa, Mastercard",
    confirmPayment: "Confirmar Pago",
    foodScan: "Escáner de Comida",
    scanCTA: "Escanear Comida",
    analyzing: "IA Analizando Comida...",
    calories: "Calorías",
    protein: "Proteína",
    carbs: "Carbohidratos",
    fat: "Grasa",
    takePhoto: "Tomar Foto",
    uploadImage: "Subir Imagen",
    analysisResult: "Análisis Nutricional",
    insufficientTokens: "Tokens insuficientes (se requieren 50)."
  },
  [Language.HI]: {
    heroTitle: "अपनी क्षमता अनलॉक करें",
    heroSub: "हमारे विशेष समुदाय में शामिल होने के लिए गहरे व्यवहारिक और शारीरिक परीक्षण पास करें।",
    ctaTests: "परीक्षण शुरू करें",
    ctaTokens: "टोकन प्राप्त करें",
    balance: "शेष राशि",
    langSwitch: "EN",
    reviews: "उपयोगकर्ता समीक्षाएं",
    startTest: "परीक्षण शुरू करें",
    continue: "आगे बढ़ें",
    back: "पीछे",
    finish: "समाप्त करें",
    results: "आपके परिणाम",
    joinChannel: "निजी चैनल में शामिल हों",
    agentPanel: "एजेंट डैशबोर्ड",
    adminPanel: "एडमिन पैनल",
    sendTokens: "टोकन भेजें",
    recipient: "प्राप्तकर्ता आईडी",
    amount: "राशि",
    success: "सफलता!",
    tokenHistory: "टोकन इतिहास",
    allTestsPackage: "पूर्ण बंडल (5 परीक्षण)",
    buyBundle: "450 टोकन के लिए बंडल खरीदें",
    price: "कीमत",
    footerCaption: "डेटा-आधारित अंतर्दृष्टि और शारीरिक उत्कृष्टता के माध्यम से आपकी यात्रा को सशक्त बनाना।",
    recentResults: "मेरे हालिया परिणाम",
    noResults: "अभी तक कोई परीक्षण पूरा नहीं हुआ है।",
    quickStart: "त्वरित शुरुआत",
    myAccount: "मेरा खाता",
    profile: "प्रोफाइल",
    buyTokens: "टोकन खरीदें",
    packageStarter: "स्टार्टर पैक",
    packagePro: "प्रो पैक",
    packageElite: "एलीट पैक",
    tokensCount: "टोकन",
    buyNow: "अभी खरीदें",
    transactionHistory: "लेनदेन का इतिहास",
    accountStats: "खाता आंकड़े",
    selectCurrency: "मुद्रा चुनें",
    payWithCrypto: "क्रिप्टो के साथ भुगतान करें",
    payWithCard: "कार्ड के साथ भुगतान करें",
    cryptoSubtitle: "तेज़ और गुमनाम",
    cardSubtitle: "वीज़ा, मास्टरकार्ड",
    confirmPayment: "भुगतान की पुष्टि करें",
    foodScan: "फूड स्कैनर",
    scanCTA: "अपना भोजन स्कैन करें",
    analyzing: "एआई भोजन का विश्लेषण कर रहा है...",
    calories: "कैलोरी",
    protein: "प्रोटीन",
    carbs: "कार्ब्स",
    fat: "वसा",
    takePhoto: "फोटो लें",
    uploadImage: "छवि अपलोड करें",
    analysisResult: "पोषण संबंधी विश्लेषण",
    insufficientTokens: "अपर्याप्त टोकन (50 आवश्यक)।"
  }
};

const createOptions = (en: [string, string, string], ru: [string, string, string], es: [string, string, string], hi: [string, string, string]) => [
  { id: Math.random().toString(36).substr(2, 9), weight: 1, text: { [Language.EN]: en[0], [Language.RU]: ru[0], [Language.ES]: es[0], [Language.HI]: hi[0] } },
  { id: Math.random().toString(36).substr(2, 9), weight: 3, text: { [Language.EN]: en[1], [Language.RU]: ru[1], [Language.ES]: es[1], [Language.HI]: hi[1] } },
  { id: Math.random().toString(36).substr(2, 9), weight: 5, text: { [Language.EN]: en[2], [Language.RU]: ru[2], [Language.ES]: es[2], [Language.HI]: hi[2] } },
];

export const MOCK_TESTS: TestDefinition[] = [
  {
    id: 't1',
    type: 'energy',
    priceTokens: 100,
    title: { [Language.EN]: 'Energy Level', [Language.RU]: 'Уровень энергии', [Language.ES]: 'Nivel de Energía', [Language.HI]: 'ऊर्जा स्तर' },
    description: { [Language.EN]: 'Assess your mental and physical stamina.', [Language.RU]: 'Оцените свою ментальную и физическую выносливость.', [Language.ES]: 'Evalúa tu resistencia mental y física.', [Language.HI]: 'अपनी मानसिक और शारीरिक सहनशक्ति का आकलन करें।' },
    questions: [
      { id: 'q1-1', text: { [Language.EN]: 'How do you feel in the morning?', [Language.RU]: 'Как вы чувствуете себя утром?', [Language.ES]: '¿Cómo te sientes por la mañana?', [Language.HI]: 'सुबह आप कैसा महसूस करते हैं?' }, options: createOptions(['Exhausted', 'Neutral', 'Energized'], ['Истощенным', 'Нейтрально', 'Бодро'], ['Agotado', 'Neutral', 'Energizado'], ['थका हुआ', 'तटस्थ', 'ऊर्जावान']) },
      { id: 'q1-2', text: { [Language.EN]: 'How many hours of sleep do you get?', [Language.RU]: 'Сколько часов вы спите?', [Language.ES]: '¿Cuántas horas duermes?', [Language.HI]: 'आप कितने घंटे सोते हैं?' }, options: createOptions(['Less than 5', '6-7 hours', '8+ hours'], ['Меньше 5', '6-7 часов', '8+ часов'], ['Menos de 5', '6-7 horas', '8+ horas'], ['5 से कम', '6-7 घंटे', '8+ घंटे']) },
      { id: 'q1-3', text: { [Language.EN]: 'Do you experience an afternoon slump?', [Language.RU]: 'Бывает ли у вас дневной упадок сил?', [Language.ES]: '¿Sufres de cansancio por la tarde?', [Language.HI]: 'क्या आप दोपहर में सुस्ती महसूस करते हैं?' }, options: createOptions(['Every day', 'Sometimes', 'Never'], ['Каждый день', 'Иногда', 'Никогда'], ['Cada día', 'A veces', 'Nunca'], ['हर दिन', 'कभी-कभी', 'कभी नहीं']) },
      { id: 'q1-4', text: { [Language.EN]: 'How is your mental focus?', [Language.RU]: 'Как ваша ментальная концентрация?', [Language.ES]: '¿Cómo es tu enfoque mental?', [Language.HI]: 'आपका मानसिक फोकस कैसा है?' }, options: createOptions(['Scattered', 'Average', 'Razor sharp'], ['Рассеянная', 'Средняя', 'Острая'], ['Disperso', 'Promedio', 'Muy agudo'], ['बिखरा हुआ', 'औसत', 'बहुत तेज']) },
      { id: 'q1-5', text: { [Language.EN]: 'Dependency on caffeine?', [Language.RU]: 'Зависимость от кофеина?', [Language.ES]: '¿Dependencia de la caffeine?', [Language.HI]: 'कैफीन पर निर्भरता?' }, options: createOptions(['High', 'Moderate', 'None'], ['Высокая', 'Умеренная', 'Нет'], ['Alta', 'Moderada', 'Ninguna'], ['अधिक', 'मध्यम', 'बिल्कुल नहीं']) },
      { id: 'q1-6', text: { [Language.EN]: 'How often do you exercise?', [Language.RU]: 'Как часто вы тренируетесь?', [Language.ES]: '¿Con qué frecuencia haces ejercicio?', [Language.HI]: 'आप कितनी बार व्यायाम करते हैं?' }, options: createOptions(['Rarely', '1-2 times/week', '3+ times/week'], ['Редко', '1-2 раза в неделю', '3+ раза в неделю'], ['Raramente', '1-2 veces/semanal', '3+ veces/semanal'], ['कभी-कभी', '1-2 बार/सप्ताह', '3+ बार/सप्ताह']) },
      { id: 'q1-7', text: { [Language.EN]: 'Recovery after a long day?', [Language.RU]: 'Восстановление после долгого дня?', [Language.ES]: '¿Recuperación tras un largo día?', [Language.HI]: 'लंबे दिन के बाद रिकवरी?' }, options: createOptions(['Difficult', 'Standard', 'Fast'], ['Трудное', 'Стандартное', 'Быстрое'], ['Difícil', 'Estándar', 'Rápida'], ['मुश्किल', 'सामान्य', 'तेज़']) },
      { id: 'q1-8', text: { [Language.EN]: 'Stress tolerance level?', [Language.RU]: 'Уровень стрессоустойчивости?', [Language.ES]: '¿Nivel de tolerancia al estrés?', [Language.HI]: 'तनाव सहन करने का स्तर?' }, options: createOptions(['Low', 'Moderate', 'High'], ['Низкий', 'Средний', 'Высокий'], ['Baja', 'Moderada', 'Alta'], ['कम', 'मध्यम', 'उच्च']) },
      { id: 'q1-9', text: { [Language.EN]: 'Mood stability?', [Language.RU]: 'Стабильность настроения?', [Language.ES]: '¿Стабильность настроения?', [Language.HI]: 'मूड की स्थिरता?' }, options: createOptions(['Unstable', 'Normal', 'Very stable'], ['Нестабильное', 'Нормальное', 'Очень стабильное'], ['Inestable', 'Normal', 'Muy stable'], ['अस्थिर', 'सामान्य', 'बहुत स्थिर']) },
      { id: 'q1-10', text: { [Language.EN]: 'General motivation?', [Language.RU]: 'Общая мотивация?', [Language.ES]: '¿Motivación general?', [Language.HI]: 'सामान्य प्रेरणा?' }, options: createOptions(['Low', 'Balanced', 'High'], ['Низкая', 'Сбалансированная', 'Высокая'], ['Baja', 'Equilibrada', 'Alta'], ['कम', 'संतुलित', 'उच्च']) },
    ]
  },
  {
    id: 't2',
    type: 'flexibility',
    priceTokens: 100,
    title: { [Language.EN]: 'Flexibility', [Language.RU]: 'Гибкость', [Language.ES]: 'Flexibilidad', [Language.HI]: 'लचीलापन' },
    description: { [Language.EN]: 'Physical mobility and stretch assessment.', [Language.RU]: 'Оценка физической мобильности и растяжки.', [Language.ES]: 'Evaluación de movilidad física y estiramiento.', [Language.HI]: 'शारीरिक गतिशीलता और खिंचाव का आकलन।' },
    questions: [
      { id: 'q2-1', text: { [Language.EN]: 'Can you touch your toes?', [Language.RU]: 'Можете ли вы коснуться пальцев ног?', [Language.ES]: '¿Puedes tocarte los pies?', [Language.HI]: 'क्या आप अपने पैर की उंगलियों को छू सकते हैं?' }, options: createOptions(['No way', 'With effort', 'Easily'], ['Никак нет', 'С трудом', 'Легко'], ['Imposible', 'Con esfuerzo', 'Fácilmente'], ['बिल्कुल नहीं', 'प्रयास के साथ', 'आसानी से']) },
      { id: 'q2-2', text: { [Language.EN]: 'Shoulder mobility?', [Language.RU]: 'Подвижность плеч?', [Language.ES]: '¿Movilidad de hombros?', [Language.HI]: 'कंधों की गतिशीलता?' }, options: createOptions(['Tight', 'Average', 'Very mobile'], ['Скованно', 'Средне', 'Очень подвижно'], ['Tensa', 'Promedio', 'Muy móvil'], ['तंग', 'औसत', 'बहुत गतिशील']) },
      { id: 'q2-3', text: { [Language.EN]: 'Deep squat comfort?', [Language.RU]: 'Комфорт в глубоком приседе?', [Language.ES]: '¿Comodidad en sentadilla profunda?', [Language.HI]: 'गहरी स्क्वाट में आराम?' }, options: createOptions(['Uncomfortable', 'Manageable', 'Natural'], ['Дискомфортно', 'Терпимо', 'Естественно'], ['Incómodo', 'Manejable', 'Natural'], ['असहज', 'प्रबंधनीय', 'स्वाभाविक']) },
      { id: 'q2-4', text: { [Language.EN]: 'Morning stiffness?', [Language.RU]: 'Утренняя скованность?', [Language.ES]: '¿Rigidez matutina?', [Language.HI]: 'सुबह की जकड़न?' }, options: createOptions(['Severe', 'Mild', 'None'], ['Сильная', 'Легкая', 'Нет'], ['Grave', 'Leve', 'Ninguna'], ['गंभीर', 'हल्की', 'बिल्कुल नहीं']) },
      { id: 'q2-5', text: { [Language.EN]: 'Back flexibility?', [Language.RU]: 'Гибкость спины?', [Language.ES]: '¿Flexibilidad de espalda?', [Language.HI]: 'पीठ का लचीलापन?' }, options: createOptions(['Stiff', 'Flexible', 'Contortionist'], ['Жесткая', 'Гибкая', 'Как у акробата'], ['Rígida', 'Flexible', 'Contorsionista'], ['कठोर', 'लचीला', 'बहुत लचीला']) },
      { id: 'q2-6', text: { [Language.EN]: 'Hamstring tightness?', [Language.RU]: 'Напряжение подколенных сухожилий?', [Language.ES]: '¿Tensión en isquiotibiales?', [Language.HI]: 'हैमस्ट्रिंग की जकड़न?' }, options: createOptions(['Very tight', 'Normal', 'Loose'], ['Очень сильное', 'Норма', 'Свободно'], ['Muy tensos', 'Normal', 'Sueltos'], ['बहुत तंग', 'सामान्य', 'ढीला']) },
      { id: 'q2-7', text: { [Language.EN]: 'Neck range of motion?', [Language.RU]: 'Диапазон движений шеи?', [Language.ES]: '¿Rango de movimiento del cuello?', [Language.HI]: 'गर्दन की गति की सीमा?' }, options: createOptions(['Limited', 'Good', 'Full'], ['Ограничен', 'Хороший', 'Полный'], ['Limitado', 'Bueno', 'Completo'], ['सीमित', 'अच्छा', 'पूर्ण']) },
      { id: 'q2-8', text: { [Language.EN]: 'Hip mobility?', [Language.RU]: 'Подвижность бедер?', [Language.ES]: '¿Movilidad de cadera?', [Language.HI]: 'कूल्हे की गतिशीलता?' }, options: createOptions(['Locked', 'Normal', 'Fluid'], ['Заблокировано', 'Норма', 'Свободно'], ['Bloqueada', 'Normal', 'Fluida'], ['लॉक', 'सामान्य', 'तरल']) },
      { id: 'q2-9', text: { [Language.EN]: 'Frequency of stretching?', [Language.RU]: 'Частота растяжки?', [Language.ES]: '¿Frecuencia de estiramiento?', [Language.HI]: 'स्ट्रेचिंग की आवृत्ति?' }, options: createOptions(['Never', 'Weekly', 'Daily'], ['Никогда', 'Раз в неделю', 'Ежедневно'], ['Nunca', 'Semanalmente', 'Diariamente'], ['कभी नहीं', 'साप्ताहिक', 'दैनिक']) },
      { id: 'q2-10', text: { [Language.EN]: 'Ankle mobility?', [Language.RU]: 'Подвижность голеностопа?', [Language.ES]: '¿Movilidad de tobillo?', [Language.HI]: 'टखने की गतिशीलता?' }, options: createOptions(['Poor', 'Fair', 'Great'], ['Плохая', 'Средняя', 'Отличная'], ['Pobre', 'Aceptable', 'Excelente'], ['खराब', 'ठीक', 'बहुत अच्छा']) },
    ]
  }
];
